name: Build and Push Docker Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Push Docker RBIS Image	
    runs-on: ubuntu-18.04	
    steps:	
    - uses: actions/checkout@master	
      with: 	
        repository: kartoza/RBIS
        ref: develop	
        fetch-depth: 1	
        path: rbis/	
    - name: Build and Publish the Docker RBIS Image	
      uses: elgohr/Publish-Docker-Github-Action@master	
      with:	
        name: ${{ secrets.IMAGE_RBIS_NAME }}:${{ secrets.IMAGE_DEVELOP_VERSION }}	
        workdir: rbis/deployment/production/uwsgi	
        username: ${{ secrets.DOCKER_USERNAME }}	
        password: ${{ secrets.DOCKER_PASSWORD }}	
        buildargs: BIMS_TAG=v3.0
